---
title: "MobiLipid: A Tool for Enhancing CCS Quality Control of IM-MS Lipidomics by Internal Standardization"
output:
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float: true
    theme: flatly
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
mainfont: "Arial"
always_allow_html: true
abstract: 'This R markdown consists of 2 parts:
First, it calculates the CCS bias between measured CCS values of U^13^C labeled yeast lipids compared to ^DT^CCS~N2~ values of a CCS library.
Secondly, the ^DT^CCS~N2~ library is used to generate up to 100 linear correction functions using 3 - 6 U^13^C labeled lipids for each lipid class-adduct combination. All measured IM values are converted with each function to an internal lipid class- and adduct-specific corrected CCS value. The CCS correction is only applied when at least 3 lipids are detected for a lipid class-adduct combination to ensure proper linear regression.'
---

```{r Load required packages and data , eval=knitr::is_html_output(), echo=FALSE, include=FALSE}
library(tcltk)
library(data.table)
library(ggplot2)
library(DT)
library(webshot)
library(knitr)

# Init Step to make sure that the dependencies are loaded
htmltools::tagList(datatable(cars))

# Choose markdown file, to also get folder path and information for file names
if (!(exists("folder_path"))) {
Rmd <- tcltk::tk_choose.files(caption = "Select R markdown (.Rmd file) which should be used for data processing:",
                              filters = matrix(c("Rmd files", "Rmd"), 1, 2),
                              multi = FALSE)
Rmd_name <- basename(Rmd)
Rmd_name <- gsub("\\.Rmd$", "", Rmd_name)

# Get file path where the markdown is saved to save results in the same folder
folder_path <- dirname(Rmd)
}

# Import of measured data:
## Column headers needed: File, LipidClass, LipidSpecies, Adduct, Label, CCS (LipidClass and LipidSpecies nomenclauture has to be as in library)
if (!(exists("data_import"))) {
  data_import <- tk_choose.files(caption = "Data import (measured data as CSV file):", multi = FALSE, filters = matrix(c("csv files", "csv"), 1, 2))
  filename <- basename(data_import)
  filename <- gsub("\\.csv$", "", filename)
  }
data_import <- fread(data_import)

# Specify the path where you want to create the folder
folder_path_new <- paste0(folder_path, "/", Rmd_name, "_", filename)


# Check if the folder already exists
if (!file.exists(folder_path_new)) {
  # If it doesn't exist, create the folder
  dir.create(folder_path_new)
}

# Import U13C labeled lipid CCS library
U13C_CCS_library <- tk_choose.files(caption = "Import CSV file of U13C labeled lipid CCS library:", multi = FALSE, filters = matrix(c("csv files", "csv"), 1, 2))
U13C_CCS_library <- fread(U13C_CCS_library)
```

```{r CCS bias calculation, eval=knitr::is_html_output(), echo=FALSE, fig.align="center", fig.height=10, fig.width=15, warning=FALSE, results="asis"}
# combine data to one data table
report <- data_import[U13C_CCS_library[,!"Mz"], on=.(LipidClass,LipidSpecies,Adduct)]
report <- report[complete.cases(report[,File])]
report[Label == "light", U13C_DTCCS := NA]

# factor for Label, so that light data is shown before heavy
report[, Label := factor(Label, levels = c("light","heavy"))]
report[, Adduct := factor(Adduct, levels = c("[M+H]","[M+NH4]","[M+Na]","[M-H]","[M+HCOO]"))]

report_bias <- copy(report)
report_bias[,CCS_bias := (CCS-U13C_DTCCS)/U13C_DTCCS*100]
report_bias <- report_bias[complete.cases(CCS_bias)]
report_bias[, Lipid_count := .N, by=.(LipidClass,Adduct)]

CCS_bias_plot <-
  ggplot(data=report_bias, aes(x=LipidClass,y=CCS_bias)) +
  theme_bw() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_violin(aes(color = LipidClass, fill = LipidClass), trim = FALSE, alpha = 0.3) +
  ggbeeswarm::geom_quasirandom(aes(color = LipidClass), na.rm = TRUE) +
  geom_point(data = report_bias[Lipid_count == 1],aes(color = LipidClass)) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  facet_grid(Adduct~.) +
  labs(x = "Lipid class", y="CCS bias %") +
  theme(legend.position = "none", text = element_text(size = 14))

results <- list()
report_bias <- report_bias[,c("File", "LipidClass", "LipidSpecies", "Polarity", "Adduct", "Label", "Formula", "CCS", "U13C_DTCCS", "CCS_bias")]
report_bias[,CCS := round(CCS, digits = 2)]
report_bias[,CCS_bias := round(CCS_bias, digits = 2)]

fwrite(report_bias, file = paste0(folder_path_new, "/CCS_bias_no_correction_",filename,".csv"))

results[["File"]] <- report_bias[,unique(File)]

report_bias <- report_bias[, c("LipidClass","LipidSpecies","Adduct","CCS","U13C_DTCCS","CCS_bias")]
results[["CCS_bias"]][["dt_CCS_bias"]] <- report_bias

results[["CCS_bias"]][["plot_CCS_bias"]] <- CCS_bias_plot

rm(list=ls()[! ls() %in% c("U13C_CCS_library","data_import","report","results","filename","folder_path_new")])

```

```{r CCS correction, echo=FALSE, warning=FALSE, results="asis", fig.align="center", fig.width=15, fig.height=10, eval=knitr::is_html_output()}
class_adduct_combination <- unique(report[, c("LipidClass", "Adduct")])

results_correction <- lapply(1:nrow(class_adduct_combination), function(k) {
  # Lipid class and adduct to look at
  class <- class_adduct_combination[k,1]
  class <- as.character(class[,LipidClass])
  adduct <- class_adduct_combination[k,2]
  adduct <- as.character(adduct[,Adduct])
  
  result_list <- list()
  result_list[["Lipid_info"]] <- paste0(class,", ",adduct)

  # filter data accordingly to lipid class and adduct
  dt_class <- report[LipidClass == class & Adduct == adduct]
  
  # only C13 for internal correction functions
  dt_class_heavy <- dt_class[Label == "heavy"]
  
  # calculate the number of lipids
  lipids_count <- as.numeric(length(unique(dt_class_heavy[,LipidSpecies])))
  
  result_list[["Lipid_count"]] <- paste0("Number of lipids: ", lipids_count)

  if (lipids_count > 2) {
    result_list[["Correction"]] <- "Correction done."

    # vector with different sampling numbers
    vector_x <- as.numeric(3:ifelse(lipids_count > 6, 6, lipids_count))
    result_list[["vector_x"]] <- vector_x
    
    # Number of elements to sample taken from vector
    result_list_sampling <- lapply(1:length(vector_x), function(j){
      x <- vector_x[j]
      result_list_element <- list()
      
      # additionally calculate max number of combinations for x number of elements which are taken for sampling
      max_combinations = choose(lipids_count, x)
      result_list_element[["max_combinations"]] <- paste0("Max. combinations: ", max_combinations)

      # Number of resampling iterations
      n = ifelse(max_combinations > 100, 100, max_combinations) 
      result_list_element[["resampling_count"]] <- paste0("Numbers of iterations for resampling: ", n)

      # Perform resampling
      # and ensure that no duplicated lipid combinations are sampled
      resampled_results <- vector("list", length = n)
      for (i in 1:n) {
        sampled_data <- sample(dt_class_heavy[,LipidSpecies], x, replace = FALSE)
        sampled_data <- sort(sampled_data)
        
        while(TRUE %in% sapply(resampled_results, identical, sampled_data)) {
          sampled_data <- sample(dt_class_heavy[,LipidSpecies], x, replace = FALSE)
          sampled_data <- sort(sampled_data)
        }
        resampled_results[[i]] <- sampled_data
      }
      result_list_element[["resampled_results"]] <- resampled_results
      
      # checks that there are no duplicated vectors in the resampled list
      resampled_vectors_string <- sapply(resampled_results, paste, collapse = ", ")
      has_duplicates <- any(duplicated(resampled_vectors_string))
      result_list_element[["duplicates_resampled_data"]] <-
        if (has_duplicates) {
          "There are duplicates in the resampled lipid combinations."
        } else {
          "No duplicates found in the resampled lipid combinations."
        }

      # correction functions for resampled data
      correction_function_dt <- data.table(function_nr = numeric(0),slope = numeric(0),intercept = numeric(0),Rsquared = numeric(0))
      correction_function_dt <- lapply(1:n, function(i) {
        correction_func <- lm(U13C_DTCCS ~ CCS, data = dt_class_heavy[LipidSpecies %in% resampled_results[[i]]])
        new_row <- data.table(function_nr = i, slope = correction_func$coefficients[2], intercept = correction_func$coefficients[1], Rsquared = summary(correction_func)$r.squared)
        return(new_row)
      })
      correction_function_dt <- rbindlist(correction_function_dt)
      
      correction_function_dt[, slope := round(slope, digits = 2)]
      correction_function_dt[, intercept := round(intercept, digits = 2)]
      correction_function_dt[, Rsquared := round(Rsquared, digits = 2)]
      correction_function_dt[, LipidClass := class]
      correction_function_dt[, Adduct := adduct]
      correction_function_dt[, Lipids_for_correction := x]
      correction_function_dt <- correction_function_dt[,c("LipidClass", "Adduct", "Lipids_for_correction", "function_nr", "slope", "intercept", "Rsquared")]
      result_list_element[["correction_functions_dt"]] <- correction_function_dt
      
      # calculate corrected CCS with correction function
      dt_class[, c("function_nr","slope","intercept","Rsquared","CCS_corrected") := NA_real_]
      
      dt_class_correction <- lapply(1:n, function(i) {
        subset <- copy(dt_class)
        subset[, function_nr := as.numeric(i)]
        subset[, slope := correction_function_dt[function_nr == i, slope]]
        subset[, intercept := correction_function_dt[function_nr == i, intercept]]
        subset[, Rsquared := correction_function_dt[function_nr == i, Rsquared]]
        subset[, CCS_corrected := (slope * CCS) + intercept]
      })
      dt_class_correction <- rbindlist(dt_class_correction)
      
      # calculate bias for CCS before and after correction
      dt_class_correction[, CCS_bias := (CCS-U13C_DTCCS)/U13C_DTCCS*100]
      dt_class_correction[, CCS_bias_corrected := (CCS_corrected-U13C_DTCCS)/U13C_DTCCS*100]
      
      # wide to long for ggplots + some restructuring
      dt_class_correction_long <- melt(dt_class_correction, id.vars = c("File", "LipidClass", "LipidSpecies", "Formula", "Polarity", "Adduct", "Label", "U13C_DTCCS", "CCS", "CCS_corrected", "function_nr", "slope", "intercept"), measure=patterns("^CCS_bias"), value.name = "CCS_bias")
      dt_class_correction_long <- dt_class_correction_long[variable == "CCS_bias" & function_nr == 1 | variable == "CCS_bias_corrected"]
      dt_class_correction_long[variable == "CCS_bias" & function_nr == 1, function_nr := 0]
      dt_class_correction_long[function_nr == 0, c("CCS_corrected","slope","intercept") := NA]
      dt_class_correction_long[, Number_lipids_correction_function := x]
      dt_class_correction_long[variable == "CCS_bias", Number_lipids_correction_function := 0]
      
      correction_results <- copy(dt_class_correction_long)
      correction_results <- correction_results[variable == "CCS_bias_corrected"]
      correction_results <- correction_results[, c("LipidClass", "LipidSpecies", "Adduct", "Label", "Number_lipids_correction_function", "function_nr", "CCS_corrected", "CCS_bias")]
      colnames(correction_results)[colnames(correction_results) == "Number_lipids_correction_function"] <- "Lipids_for_correction"
      
      correction_results <- correction_results[complete.cases(CCS_corrected)]
      result_list_element[["correction_results"]] <- correction_results
      
      correction_results_mean <- correction_results[, .(mean_CCS_corrected = mean(CCS_corrected, na.rm = TRUE), sd_CCS_corrected = sd(CCS_corrected, na.rm = TRUE)), by = .(LipidClass, LipidSpecies, Adduct, Label, Lipids_for_correction)]
      
      result_list_element[["correction_results_mean"]] <- correction_results_mean
      
      # mean bias calculation
      dt_class_adduct_mean_bias <- dt_class_correction_long[, .(mean_CCS_bias = mean(CCS_bias, na.rm = TRUE), sd_CCS_bias = sd(CCS_bias, na.rm = TRUE)), by = .(File, LipidClass, Polarity, Adduct, Number_lipids_correction_function, Label, variable)]
      dt_class_adduct_mean_bias <- dt_class_adduct_mean_bias[mean_CCS_bias != "NaN"] 
      dt_class_adduct_mean_bias[, mean_CCS_bias := round(mean_CCS_bias, digits = 2)]
      dt_class_adduct_mean_bias[, sd_CCS_bias := round(sd_CCS_bias, digits = 2)]
      
      result_list_element[["bias_over_all_functions"]] <- dt_class_adduct_mean_bias
      
      dt_class_adduct_mean_bias_byfunction <- dt_class_correction_long[, .(mean_CCS_bias = mean(CCS_bias, na.rm = TRUE), sd_CCS_bias = sd(CCS_bias, na.rm = TRUE)), by = .(File, LipidClass, Polarity, Adduct, Label, variable, function_nr)]
      dt_class_adduct_mean_bias_byfunction <- dt_class_adduct_mean_bias_byfunction[mean_CCS_bias != "NaN"] 
      dt_class_adduct_mean_bias_byfunction[, mean_CCS_bias := round(mean_CCS_bias, digits = 2)]
      dt_class_adduct_mean_bias_byfunction[, sd_CCS_bias := round(sd_CCS_bias, digits = 2)]
      dt_class_adduct_mean_bias_byfunction[, Lipids_for_correction := as.character(x)]
      dt_class_adduct_mean_bias_byfunction[function_nr == 0, Lipids_for_correction := "No correction"]
      dt_class_adduct_mean_bias_byfunction[, function_nr := as.character(function_nr)]
      dt_class_adduct_mean_bias_byfunction[function_nr == "0", function_nr := "No correction"]
      dt_class_adduct_mean_bias_byfunction <- dt_class_adduct_mean_bias_byfunction[,c("LipidClass", "Adduct", "Lipids_for_correction", "function_nr", "mean_CCS_bias", "sd_CCS_bias")]
      
      result_list_element[["bias_by_each_functions"]] <- dt_class_adduct_mean_bias_byfunction
      
      colnames(dt_class_adduct_mean_bias_byfunction) <- c("Lipid Class", "Adduct", "Lipids_for_correction", "Correction function", "Mean CCS bias (%)", "Standard deviation (%)")
      
      # violin plot for bias before and after correction
      result_plots <- list()
      
      dt_plotting <- copy(dt_class_correction_long) 
      # add column for better plotting
      if (dt_plotting[, length(unique(function_nr))] <= 25) {
        dt_plotting[, plot := 1]
      }
      if (dt_plotting[, length(unique(function_nr))] > 25 & dt_plotting[, length(unique(function_nr))] <= 50) {
        dt_plotting[, plot := cut(function_nr, breaks = 2, labels = FALSE)]
      }
      if (dt_plotting[, length(unique(function_nr))] > 50 & dt_plotting[, length(unique(function_nr))] <= 75) {
        dt_plotting[, plot := cut(function_nr, breaks = 3, labels = FALSE)]
      }
      if (dt_plotting[, length(unique(function_nr))] > 75) {
        dt_plotting[, plot := cut(function_nr, breaks = 4, labels = FALSE)]
      }          
      
      dt_plotting[,coloring := function_nr]
      dt_plotting[coloring == 0, coloring := NA]
      
      result_plots[[1]] <-
        ggplot(data=dt_plotting[Label == "heavy"], aes(x=variable,y=CCS_bias)) +
        theme_bw() +
        geom_hline(yintercept = 0, linetype = "dashed") +
        geom_violin(trim = FALSE) +
        ggbeeswarm::geom_quasirandom(aes(color=coloring), alpha = 0.75, na.rm = TRUE) +
        scale_color_viridis_c(na.value = "black") +
        scale_x_discrete(labels = c("No CCS correction", "CCS correction using all functions")) +
        labs(x=NULL, y="CCS bias (%)",color="Function\nnumber", title = paste0(result_list[["Lipid_info"]]), subtitle = paste0("Number of lipids taken for linear correction function: ",x)) +
        theme(text = element_text(size = 14))

      # violin plot for each correction function

      result_plots[[2]] <-
        ggplot(data=dt_plotting[Label == "heavy"], aes(x= factor(function_nr),y=CCS_bias)) +
        theme_bw() +
        geom_hline(yintercept = 0, linetype = "dashed") +
        geom_violin(aes(fill = coloring,color = coloring), trim = FALSE) +
        scale_fill_viridis_c(na.value = "black") +
        scale_color_viridis_c(na.value = "black") +
        facet_wrap(~plot, ncol = 1, scales = "free_x", labeller=function(x) {x[1]}) +
        scale_x_discrete(expand = c(0, 0), labels = c("0" = "No correction")) +
        theme(strip.background = element_blank(), strip.text = element_blank(), text = element_text(size = 14)) +
        labs(x="Function number", y="CCS bias (%)", color="Function\nnumber", fill="Function\nnumber", title = paste0(result_list[["Lipid_info"]]), subtitle = paste0("Number of lipids taken for linear correction function: ",x))

      result_list_element[["result_plots"]] <- result_plots
      result_list_element[["result_plots"]][["dt_plotting"]] <- dt_plotting
      
      return(result_list_element)
    })
    names(result_list_sampling) <- vector_x
    result_list <- c(result_list, result_list_sampling)
    
  } else {
    result_list[["Correction"]] <- "No correction possible."
  }
  
  if (result_list[["Correction"]] == "Correction done.") {
    
    # Violin plot including all correction functions for one lipid class - adduct - combination
    dt_plotting_all <- rbind(result_list[["3"]][["result_plots"]][["dt_plotting"]], result_list[["4"]][["result_plots"]][["dt_plotting"]], result_list[["5"]][["result_plots"]][["dt_plotting"]], result_list[["6"]][["result_plots"]][["dt_plotting"]])
    dt_plotting_all <- unique(dt_plotting_all)
    dt_plotting_all[, coloring := Number_lipids_correction_function]
    dt_plotting_all[coloring == 0, coloring := NA]
    
    result_list[["Violin_plot_all_corrections"]] <-
      ggplot(data=dt_plotting_all[Label == "heavy"], aes(x= factor(Number_lipids_correction_function),y=CCS_bias)) +
      theme_bw() +
      geom_hline(yintercept = 0, linetype = "dashed") +
      geom_violin(aes(fill= factor(coloring), color= factor(coloring)), trim = FALSE) +
      scale_color_viridis_d(na.value = "black") +
      scale_fill_viridis_d(na.value = "black") +
      scale_x_discrete(labels = c("0" = "No correction")) +
      labs(x="Numbers of lipids used to generate CCS correction function", y="CCS bias (%)", title = paste0(result_list[["Lipid_info"]])) +
      theme(text = element_text(size = 14), legend.position = "none")

    # for Correction_functions
    correction_function_dt_lipid <- lapply(min(vector_x):max(vector_x), function(i) {
      correction_function_dt <- result_list[[paste0(i)]][["correction_functions_dt"]]
    })
    correction_function_dt_lipid <- rbindlist(correction_function_dt_lipid)
    result_list[["correction_function_dt_lipid"]] <- correction_function_dt_lipid
    
    # for CCS_bias_mean_all_functions
    bias_all_functions_lipid <- lapply(min(vector_x):max(vector_x), function(i) {
      bias_all_functions <- result_list[[paste0(i)]][["bias_over_all_functions"]]
    })
    bias_all_functions_lipid <- rbindlist(bias_all_functions_lipid)
    bias_all_functions_lipid <- unique(bias_all_functions_lipid)
    bias_all_functions_lipid <- bias_all_functions_lipid[,c("LipidClass","Adduct","Number_lipids_correction_function","mean_CCS_bias","sd_CCS_bias")]
    colnames(bias_all_functions_lipid)[colnames(bias_all_functions_lipid) == "Number_lipids_correction_function"] <- "Lipids_for_correction"
    bias_all_functions_lipid[, Lipids_for_correction := as.character(Lipids_for_correction)]
    bias_all_functions_lipid[Lipids_for_correction == "0", Lipids_for_correction := as.character("No correction")]
    result_list[["bias_all_functions_lipid"]] <- bias_all_functions_lipid
    
    # for CCS_bias_mean_by_function
    bias_by_function_lipid <- lapply(min(vector_x):max(vector_x), function(i) {
      bias_by_function <- result_list[[paste0(i)]][["bias_by_each_functions"]]
    })
    bias_by_function_lipid <- rbindlist(bias_by_function_lipid)
    bias_by_function_lipid <- unique(bias_by_function_lipid)
    result_list[["bias_by_function_lipid"]] <- bias_by_function_lipid
    
    # for Corrected_CCS_values
    correction_results_lipid <- lapply(min(vector_x):max(vector_x), function(i) {
      correction_results <- result_list[[paste0(i)]][["correction_results"]]
    })
    correction_results_lipid <- rbindlist(correction_results_lipid)
    result_list[["correction_results_lipid"]] <- correction_results_lipid
    
    # for Corrected_CCS_values_mean
    correction_results_mean_lipid <- lapply(min(vector_x):max(vector_x), function(i) {
      correction_results_mean <- result_list[[paste0(i)]][["correction_results_mean"]]
    })
    correction_results_mean_lipid <- rbindlist(correction_results_mean_lipid)
    result_list[["correction_results_mean_lipid"]] <- correction_results_mean_lipid
    
  }
  return(result_list)
})

names_list <- lapply(1:nrow(class_adduct_combination), function(k) {
  # Lipid class and adduct to look at
  class <- class_adduct_combination[k,1]
  class <- as.character(class[,LipidClass])
  adduct <- class_adduct_combination[k,2]
  adduct <- as.character(adduct[,Adduct]) 

  names_list <- paste0(class, ", ", adduct)
  return(names_list)
  })

names_list <- unlist(names_list)
names(results_correction) <- names_list

results <- c(results, results_correction)

rm(list=ls()[! ls() %in% c("U13C_CCS_library", "data_import", "report", "results", "filename","class_vector", "adduct_vector", "class", "folder_path_new")])

# for Correction_functions
correction_function_dt_all <- lapply(3:length(results), function(i) {
  correction_function_dt_lipid <- results[[i]][["correction_function_dt_lipid"]]
})
correction_function_dt_all <- rbindlist(correction_function_dt_all)
fwrite(correction_function_dt_all, file = paste0(folder_path_new, "/Correction_functions_",filename,".csv"))

# for CCS_bias_mean_all_functions
bias_all_functions_all <- lapply(3:length(results), function(i) {
  bias_all_functions_lipid <- results[[i]][["bias_all_functions_lipid"]]
})
bias_all_functions_all <- rbindlist(bias_all_functions_all)
fwrite(bias_all_functions_all, file = paste0(folder_path_new, "/CCS_bias_mean_all_functions_",filename,".csv"))

# for CCS_bias_mean_by_function
bias_by_function_all <- lapply(3:length(results), function(i) {
  bias_by_function_lipid <- results[[i]][["bias_by_function_lipid"]]
})
bias_by_function_all <- rbindlist(bias_by_function_all)
fwrite(bias_by_function_all, file = paste0(folder_path_new, "/CCS_bias_mean_by_function_",filename,".csv"))

# for Corrected_CCS_values
correction_results_all <- lapply(3:length(results), function(i) {
  correction_results_lipid <- results[[i]][["correction_results_lipid"]]
})
correction_results_all <- rbindlist(correction_results_all)
fwrite(correction_results_all, file = paste0(folder_path_new, "/Corrected_CCS_values_",filename,".csv"))

# for Corrected_CCS_values_mean
correction_results_mean_all <- lapply(3:length(results), function(i) {
  correction_results_mean_lipid <- results[[i]][["correction_results_mean_lipid"]]
})
correction_results_mean_all <- rbindlist(correction_results_mean_all)
fwrite(correction_results_mean_all, file = paste0(folder_path_new, "/Corrected_CCS_values_mean_",filename,".csv"))

saveRDS(results, file = paste0(folder_path_new, "/R_results_",filename,".RData"))

```

```{r Print results to html, echo=FALSE, fig.align="center", fig.height=10, fig.width=15, warning=FALSE, results="asis", eval=knitr::is_html_output()}
cat("\n#", paste0("File: ", results[["File"]]), " {-}") 

cat("\n#", "CCS bias calculation", "  \n") 

cat("\n##","Table with CCS bias (%) between measured CCS values and ^DT^CCS~N2~ library of U^13^C labeled lipids","  \n")
datatable(results[["CCS_bias"]][["dt_CCS_bias"]], rownames = FALSE)

cat("\n##","Violin plot for CCS bias by lipid class and adduct","  \n")
plot(results[["CCS_bias"]][["plot_CCS_bias"]])
cat("  \n")

cat("\n#", "Internal CCS correction", "  \n") 

invisible(lapply(3:length(results), function(i) {
  cat("\n##",results[[i]][["Lipid_info"]], "  \n")
  cat(results[[i]][["Lipid_count"]],"  \n")
  
  if (results[[i]][["Correction"]] == "Correction done.") {
    cat(results[[i]][["Correction"]],"  \n")

    lapply(1:length(results[[i]][["vector_x"]]), function(j) {
      x <- results[[i]][["vector_x"]][j]
      cat("\n###","Number of lipids taken for linear correction function: ",x , "  \n")
      cat(results[[i]][[paste0(x)]][["max_combinations"]],"  \n")
      cat(results[[i]][[paste0(x)]][["resampling_count"]],"  \n")
      cat(results[[i]][[paste0(x)]][["duplicates_resampled_data"]],"  \n")
      
      cat("\n####", "Correction functions", "  \n")
      cat("y = m * x + b","  \n" ,"Input:","  \n","x = Measured CCS of U^13^C labeled lipid","  \n", "y = ^DT^CCS~N2~ of U^13^C labeled lipid", "  \n")
      print(htmltools::tagList(datatable(results[[i]][[paste0(x)]][["correction_functions_dt"]], rownames = FALSE)))
      
      cat("\n####", "CCS bias", "  \n")
      cat("No CCS correction: Mean bias = ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias", mean_CCS_bias], "% +/- ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias", sd_CCS_bias],"%","  \n","Internal CCS correction (all correction functions): Mean bias = ",results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias_corrected", mean_CCS_bias], "% +/- ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias_corrected", sd_CCS_bias],"%","  \n", "  \n", sep = "")
      cat("CCS bias for each correction fuction:", "  \n")
      print(htmltools::tagList(datatable(results[[i]][[paste0(x)]][["bias_by_each_functions"]][,!"Lipids_for_correction"], rownames = FALSE)))
      
      cat("\n####","Violin plot - CCS bias: No CCS correction vs. internal CCS correction", "  \n")
      
      plot(results[[i]][[paste0(x)]][["result_plots"]][[1]])
      cat("  \n")
      
      cat("\n####","Violin plot - CCS bias distribution for each internal CCS correction function", "  \n")
      plot(results[[i]][[paste0(x)]][["result_plots"]][[2]])
      cat("  \n")
    })
    
    cat("\n###","CCS bias: All correction functions", "  \n")
    print(htmltools::tagList(datatable(results[[i]][["bias_all_functions_lipid"]], rownames = FALSE)))
    plot(results[[i]][["Violin_plot_all_corrections"]])
    cat("  \n")
    
  } else {
    cat(results[[i]][["Correction"]],"  \n")
  }
}))
```

```{r Print results to pdf, echo=FALSE, fig.align="center", fig.height=10, fig.width=15, warning=FALSE, results="asis", eval=knitr::is_latex_output(),}
cat("\n#", paste0("File: ", results[["File"]]), " {-}") 

cat("\n#", "CCS bias calculation", "  \n") 

cat("\n##","Table with CCS bias (%) between measured CCS values and ^DT^CCS~N2~ library of U^13^C labeled lipids","  \n")
kable(head(results[["CCS_bias"]][["dt_CCS_bias"]], n = 10))

cat("\n##","Violin plot for CCS bias by lipid class and adduct","  \n")
plot(results[["CCS_bias"]][["plot_CCS_bias"]])
cat("  \n")

cat("\n#", "Internal CCS correction", "  \n") 

invisible(lapply(3:length(results), function(i) {
  cat("\n##",results[[i]][["Lipid_info"]], "  \n")
  cat(results[[i]][["Lipid_count"]],"  \n")
  
  if (results[[i]][["Correction"]] == "Correction done.") {
    cat(results[[i]][["Correction"]],"  \n")

    lapply(1:length(results[[i]][["vector_x"]]), function(j) {
      x <- results[[i]][["vector_x"]][j]
      cat("\n###","Number of lipids taken for linear correction function: ",x, "  \n")
      cat(results[[i]][[paste0(x)]][["max_combinations"]],"  \n")
      cat(results[[i]][[paste0(x)]][["resampling_count"]],"  \n")
      cat(results[[i]][[paste0(x)]][["duplicates_resampled_data"]],"  \n")
      
      cat("\n####", "Correction functions", "  \n")
      cat("x = IMS value","  \n", "y = ^DT^CCS~N2~ of U^13^C labeled lipid", "  \n")
      cat("First 10 rows of table:", "  \n")
      print(kable(head(results[[i]][[paste0(x)]][["correction_functions_dt"]], n = 10)))
      
      cat("\n####", "CCS bias", "  \n")
      cat("No CCS correction: Mean bias = ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias", mean_CCS_bias], "% +/- ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias", sd_CCS_bias],"%","  \n","Internal CCS correction (all correction functions): Mean bias = ",results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias_corrected", mean_CCS_bias], "% +/- ", results[[i]][[paste0(x)]][["bias_over_all_functions"]][variable == "CCS_bias_corrected", sd_CCS_bias],"%","  \n", "  \n", sep = "")
      cat("CCS bias for each correction fuction (first 10 rows of table):", "  \n")
      print(kable(head(results[[i]][[paste0(x)]][["bias_by_each_functions"]][,!"Lipids_for_correction"], n = 10)))
      
      cat("\n####","Violin plot - CCS bias: No CCS correction vs. internal CCS correction", "  \n")
      
      plot(results[[i]][[paste0(x)]][["result_plots"]][[1]])
      cat("  \n")
      
      cat("\n####","Violin plot - CCS bias distribution for each internal CCS correction function", "  \n")
      plot(results[[i]][[paste0(x)]][["result_plots"]][[2]])
      cat("  \n")
    })
    
    cat("\n###","CCS bias: All correction functions", "  \n")
    print(kable(results[[i]][["bias_all_functions_lipid"]]))
    plot(results[[i]][["Violin_plot_all_corrections"]])
    cat("  \n")
    
    
  } else {
    cat(results[[i]][["Correction"]],"  \n")
  }
}))
```

